-- CREATE TYPE
DROP TYPE IF EXISTS Gender;
CREATE TYPE Gender AS ENUM (
    'male',
    'female'
);

-- CREATE TABLE
DROP TABLE IF EXISTS Ids;
CREATE TABLE Ids (
    Id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "Name" VARCHAR(255) NOT NULL,
    "Value" VARCHAR(255) NOT NULL
);

-- CREATE TABLE
DROP TABLE IF EXISTS Names;
CREATE TABLE Names (
    Id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Title VARCHAR(255),
    First VARCHAR(255) NOT NULL,
    Last VARCHAR(255) NOT NULL
);

-- CREATE TABLE
DROP TABLE IF EXISTS Streets;
CREATE TABLE Streets (
    Id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "Number" INT,
    "Name" VARCHAR(255) NOT NULL
);

-- CREATE TABLE
DROP TABLE IF EXISTS Coordinates;
CREATE TABLE Coordinates (
    Id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Latitude INT,
    Longitude VARCHAR(255) NOT NULL
);

-- CREATE TABLE
DROP TABLE IF EXISTS Timezones;
CREATE TABLE Timezones (
    Id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "Offset" VARCHAR(255) NOT NULL,
    "Description" VARCHAR(255) NOT NULL
);

-- CREATE TABLE
DROP TABLE IF EXISTS Locations;
CREATE TABLE Locations (
    Id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    StreetId INT REFERENCES Streets(Id),
    City VARCHAR(255) NOT NULL,
    "State" VARCHAR(255) NOT NULL,
    Country VARCHAR(255) NOT NULL,
    Postcode INTEGER,
    CoordinatesId INT REFERENCES Coordinates(Id),
    TimezoneId INT REFERENCES Timezones(Id),
    ResultId INT REFERENCES Ids(Id)
);

-- CREATE TABLE
DROP TABLE IF EXISTS Logins;
CREATE TABLE Logins (
    Id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Uuid VARCHAR(255) NOT NULL,
    Username VARCHAR(255) NOT NULL,
    "Password" VARCHAR(255) NOT NULL,
    Salt VARCHAR(255) NOT NULL,
    Md5 VARCHAR(255) NOT NULL,
    Sha1 VARCHAR(255) NOT NULL,
    Sha256 VARCHAR(255) NOT NULL,
    ResultId INT REFERENCES Ids(Id)
);

-- CREATE TABLE
DROP TABLE IF EXISTS Dobs;
CREATE TABLE Dobs (
    Id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "Date" VARCHAR(255) NOT NULL,
    Age INTEGER NOT NULL,
    ResultId INT REFERENCES Ids(Id)
);

-- CREATE TABLE
DROP TABLE IF EXISTS Registereds;
CREATE TABLE Registereds (
    Id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "Date" VARCHAR(255) NOT NULL,
    Age INTEGER NOT NULL,
    ResultId INT REFERENCES Ids(Id)
);

-- CREATE TABLE
DROP TABLE IF EXISTS Pictures;
CREATE TABLE Pictures (
    Id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Large VARCHAR(255),
    Medium VARCHAR(255),
    Thumbnail VARCHAR(255),
    ResultId INT REFERENCES Ids(Id)
);

-- CREATE TABLE
DROP TABLE IF EXISTS Results;
CREATE TABLE Results (
    Id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Gender Gender NOT NULL,
    NameId INT REFERENCES Names(Id),
    ResultId INT REFERENCES Ids(Id),
    LocationId INT REFERENCES Locations(Id),
    Email VARCHAR(255),
    Phone VARCHAR(255),
    Cell VARCHAR(255),
    Nat VARCHAR(255)
);
